version: '3.7'

services:

   #Start elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata1:/usr/share/elasticsearch/data
      - /backups:/opt/elasticsearch/backup
    ports:
      - 9200:9200
    networks:
      - elasticsearch-6-2_web
    deploy:
      replicas: 1 # replicas  cant be more than one server might crash if more are use:
     #End elasticsearch
     

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml   
    networks:
      - elasticsearch-6-2_web



  dusbe_api:
    image: dusbe-api
    networks: 
      - elasticsearch-6-2_web
    volumes:
      - /home/storage/dusbe/public/site_map_us/sitemap.xml:/usr/src/app/site_map/sitemap.xml
      - /home/storage/dusbe/public/site_map_us/273_901_dpa_product_catalog_feed_rss.xml:/usr/src/app/site_map/273_901_dpa_product_catalog_feed_rss.xml
      - /home/storage/dusbe/public/img/product/main-product:/usr/src/app/public/img/product/main-product  
      - /home/storage/dusbe/public/img/product/s-thumbnail:/usr/src/app/public/img/product/s-thumbnail  
      - /home/storage/dusbe/public/img/product/thumbnail:/usr/src/app/public/img/product/thumbnail


  dusbe_api_uk:
    image: dusbe-api-uk
    networks:
      - elasticsearch-6-2_web
    volumes:
      - /home/storage/dusbe/public/site_map_uk/sitemap.xml:/usr/src/app/site_map/sitemap.xml
      - /home/storage/dusbe/public/site_map_uk/273_901_dpa_product_catalog_feed_rss.xml:/usr/src/app/site_map/273_901_dpa_product_catalog_feed_rss.xml
      - /home/storage/dusbe/public/img/product/main-product:/usr/src/app/public/img/product/main-product
      - /home/storage/dusbe/public/img/product/s-thumbnail:/usr/src/app/public/img/product/s-thumbnail
      - /home/storage/dusbe/public/img/product/thumbnail:/usr/src/app/public/img/product/thumbnail

  #Start Web

  dusbe:
    image: dusbe
    deploy:
      replicas: 1
    networks:
      - traefik
      - elasticsearch-6-2_web
    volumes:
      - /home/storage/dusbe/public/img/product/main-product:/var/www/public/img/product/main-product
      - /home/storage/dusbe/public/img/product/s-thumbnail:/var/www/public/img/product/s-thumbnail
      - /home/storage/dusbe/public/img/product/thumbnail:/var/www/public/img/product/thumbnail
      - /home/storage/dusbe/public/img/blog/main:/var/www/public/img/blog/main
      - /home/storage/dusbe/public/img/blog/thumbnail:/var/www/public/img/blog/thumbnail
      - /home/storage/dusbe/public/img/captcha:/var/www/public/img/captcha
      - /home/storage/dusbe/data/cache/dusbe:/var/www/data/cache
      - /home/storage/dusbe/public/site_map_us/sitemap.xml:/var/www/public/site_map/sitemap.xml
      - /home/storage/dusbe/public/site_map_us/273_901_dpa_product_catalog_feed_rss.xml:/var/www/public/site_map/273_901_dpa_product_catalog_feed_rss.xml
      - /home/storage/dusbe/public/site_map_us/robots.txt:/var/www/public/robots.txt
    labels:
      - traefik.backend=traefik_traefik_us
      - traefik.docker.network=traefik
      - traefik.frontend.rule=Host:dusbe.com,www.dusbe.com
      - traefik.enable=true
      - traefik.frontend.passHostHeader=true
      - traefik.port=80

  #End web

  #Start Web

  ukdusbe:
    image: ukdusbe
    deploy:
      replicas: 1
    networks:
      - traefik
      - elasticsearch-6-2_web
    volumes:
      - /home/storage/dusbe/public/img/product/main-product:/var/www/public/img/product/main-product
      - /home/storage/dusbe/public/img/product/s-thumbnail:/var/www/public/img/product/s-thumbnail
      - /home/storage/dusbe/public/img/product/thumbnail:/var/www/public/img/product/thumbnail
      - /home/storage/dusbe/public/img/blog/main:/var/www/public/img/blog/main
      - /home/storage/dusbe/public/img/blog/thumbnail:/var/www/public/img/blog/thumbnail
      - /home/storage/dusbe/public/img/captcha:/var/www/public/img/captcha
      - /home/storage/dusbe/data/cache/ukdusbe:/var/www/data/cache
      - /home/storage/dusbe/public/site_map_uk/sitemap.xml:/var/www/public/site_map/sitemap.xml
      - /home/storage/dusbe/public/site_map_uk/273_901_dpa_product_catalog_feed_rss.xml:/var/www/public/site_map/273_901_dpa_product_catalog_feed_rss.xml
      - /home/storage/dusbe/public/site_map_uk/robots.txt:/var/www/public/robots.txt
    labels:
      - traefik.backend=traefik_traefik_uk
      - traefik.docker.network=traefik
      - traefik.frontend.rule=Host:dusbe.co.uk,www.dusbe.co.uk
      - traefik.enable=true
      - traefik.frontend.passHostHeader=true
      - traefik.port=80

  #End web

  #Start Web
 
  usdusbe:
    image: usdusbe
    deploy:
      replicas: 1
    networks:
      - traefik
      - elasticsearch-6-2_web
    volumes:
      - /home/storage/dusbe/public/img/product/main-product:/var/www/public/img/product/main-product
      - /home/storage/dusbe/public/img/product/s-thumbnail:/var/www/public/img/product/s-thumbnail
      - /home/storage/dusbe/public/img/product/thumbnail:/var/www/public/img/product/thumbnail
      - /home/storage/dusbe/public/img/blog/main:/var/www/public/img/blog/main
      - /home/storage/dusbe/public/img/blog/thumbnail:/var/www/public/img/blog/thumbnail
      - /home/storage/dusbe/public/img/captcha:/var/www/public/img/captcha
      - /home/storage/dusbe/data/cache/usdusbe:/var/www/data/cache
      - /home/storage/dusbe/public/site_map_us/sitemap.xml:/var/www/public/site_map/sitemap.xml
      - /home/storage/dusbe/public/site_map_us/273_901_dpa_product_catalog_feed_rss.xml:/var/www/public/site_map/273_901_dpa_product_catalog_feed_rss.xml
      - /home/storage/dusbe/public/site_map_us/robots.txt:/var/www/public/robots.txt
    labels:
      - traefik.backend=traefik_traefik_us_2
      - traefik.docker.network=traefik
      - traefik.frontend.rule=Host:dusbe.us,www.dusbe.us
      - traefik.enable=true
      - traefik.frontend.passHostHeader=true
      - traefik.port=80

  #End web
volumes:
  esdata1:
    driver: local
  dbdata:
  backups:
    external: true

networks:
  elasticsearch-6-2_web:
    external: false
  traefik:
     external: true
