version: '3.7'

services:

  #Start elasticsearch
  #End elasticsearch

  #Start makeupshoponline
  avononlinestore:
    image: avononlinestore
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.avononlinestore.rule=Host(`makeupshoponline.com`)"
      - "traefik.http.routers.avononlinestore.entrypoints=web"
      -  "traefik.http.routers.app.middlewares: https_redirect"

      -  "traefik.http.routers.appsecured.rule: Host(`makeupshoponline.com`)"
      -  "traefik.http.routers.appsecured.entrypoints: websecure"
      -  "traefik.http.routers.appsecured.tls: true"

      -  "traefik.http.middlewares.https_redirect.redirectscheme.scheme: https"
      -  "traefik.http.middlewares.https_redirect.redirectscheme.permanent: true"
  #End makeupshoponline
    
  #Start dusbe

  #End dusbe


networks:
  traefik:
     external: true
