version: "3.7"
services:

  traefik:
    image: traefik:v2.2
    command:
  #    - "--api.insecure=true" # set to 'false' on production
      - "--api.dashboard=true" # see https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode for how to secure the dashboard
      - "--api.debug=true" # enable additional endpoints for debugging and profiling
      - "--log.level=DEBUG" # debug while we get it working, for more levels/info see https://docs.traefik.io/observability/logs/
  #    - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - '--providers.docker.defaultRule=Host("gridwebsites.co")'
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    #  - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpChallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=dusbestore@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" #https://docs.traefik.io/https/acme/

    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.admin-auth.basicauth.users=traefik:password1234
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`gridwebsites.co`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`gridwebsites.co`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080


    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - proxy
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"



  avononlinestore:
    image: avononlinestore
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.avononlinestore.rule=Host(`makeupshoponline.com`)"
      - "traefik.http.routers.avononlinestore.entrypoints=web"


networks:
  proxy:
    driver: overlay
    external: true
    name: proxy
volumes:
  letsencrypt:
